// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 

  

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJM0D2ddohzDRhU2TEib7lc5PI8ZjJhUE',
    appId: '1:108064571615:web:aa7c03e6047c92c9e8696a',
    messagingSenderId: '108064571615',
    projectId: 'mind-308cc',
    authDomain: 'mind-308cc.firebaseapp.com',
    storageBucket: 'mind-308cc.appspot.com',
    measurementId: 'G-BVGQCPYG2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQqRRyreBGQKIGar5g4jCsJ_I2CUmlOtg',
    appId: '1:108064571615:android:283cf3041ae41f30e8696a',
    messagingSenderId: '108064571615',
    projectId: 'mind-308cc',
    storageBucket: 'mind-308cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuAVb3ActDet_-QVZYkAKx2t-a56acpg4',
    appId: '1:108064571615:ios:73525d5f12bef9e0e8696a',
    messagingSenderId: '108064571615',
    projectId: 'mind-308cc',
    storageBucket: 'mind-308cc.appspot.com',
    iosBundleId: 'com.example.mind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuAVb3ActDet_-QVZYkAKx2t-a56acpg4',
    appId: '1:108064571615:ios:d7beba36e5836fece8696a',
    messagingSenderId: '108064571615',
    projectId: 'mind-308cc',
    storageBucket: 'mind-308cc.appspot.com',
    iosBundleId: 'com.example.mind.RunnerTests',


  );
}
